########################### Default configuration ######################
baseURL = "https://cloudnative.to/"
title = "云原生社区"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disable language
disableLanguages = [] # desable language from here
hasCJKLanguage = true
DefaultContentLanguage = "zh"

[outputs]
home = ["HTML", "RSS", "JSON"]

############################### Plugins #################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/fontawesome/font-awesome.min.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/bigPicture/bigPicture.js"
[[params.plugins.js]]
link = "plugins/hex_md5/hex_md5.js"

########################### navigation ################################
# main menu
[[menu.main]]
name = "Community"
weight = 2

[[menu.main]]
parent = "Community"
name = "About"
URL = "about"
weight = 1

[[menu.main]]
parent = "Community"
name = "Steering Committee"
URL = "team"
weight = 2

[[menu.main]]
parent = "Community"
name = "Kubernetes SIG"
URL = "https://i.cloudnative.to/kubernetes/"
weight = 3

[[menu.main]]
parent = "Community"
name = "Istio SIG"
URL = "https://i.cloudnative.to/istio/"
weight = 4

[[menu.main]]
parent = "Community"
name = "Envoy SIG"
URL = "https://i.cloudnative.to/envoy/"
weight = 5

[[menu.main]]
parent = "Community"
name = "Dapr SIG"
URL = "https://i.cloudnative.to/dapr/"
weight = 6

[[menu.main]]
parent = "Community"
name = "OAM SIG"
URL = "https://i.cloudnative.to/oam/"
weight = 7

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 4

[[menu.main]]
name = "Contribute"
URL = "contribute"
weight = 5

[[menu.main]]
name = "Job"
URL = "job"
weight = 6

# [[menu.main]]
# weight = 8
# name = "Pages"
# hasChildren = true
#
#   [[menu.main]]
#   parent = "Pages"
#   name = "Project"
#   URL = "project"

# footer menu
[[menu.footer]]
name = "Announcement and Policy"
URL = "/code-of-conduct"
weight = 1

########################### Default parameters ######################
[params]
logo = "images/logo.png"
logo_footer = "images/logo-alt.png"
# top header
top_header = false
# Meta data
description = "云原生社区是一个中立的云原生终端用户社区，由 CNCF 大使、开源意见领袖共同发起成立于 2020 年 5 月 12 日，旨在推广云原生技术，构建开发者生态。"
author = " 云原生社区"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-93485976-4" # your id
# Baidu tongji
baidu_tongji_id = "f3dc895ea3bd6186cd835841d365c103"
# page sidebar quick contact form
quick_contact = false
# search
search = true
map = false
email = "[contact@cloudnative.to](mailto:contact@cloudnative.to)"
wechat = "[jimmysongio](https://jimmysong.io/contact)"
address = "请关注云原生社区城市站"

# Gitalk
enableGitalk = true

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
link = "contact"

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

[params.gitalk]
clientID = "0f001988910adcfadfb7" # Your client ID
clientSecret = "14f7d06ee5e6575c295d18fc11616e8cb60fb84e" # Your client secret
repo = "cloudnativeto.github.io" # The repo to store comments
owner = "cloudnativeto" # Your GitHub ID
admin= "rootsongjc" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
id= "location.pathname" # The unique id of the page.
labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
perPage= 15 # Pagination size, with maximum 100.
pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.

########################### social icon ############################
[[params.social]]
icon = "fa-twitter"
link = "https://twitter.com/cloudnativecn"

[[params.social]]
icon = "fa-github"
link = "https://github.com/cloudnativeto"

#[[params.social]]
#icon = "fa-slack"
#link = "https://cloudnativecommunity.slack.com"

[[params.social]]
icon = "fa-wechat"
# change the link after the public announcement
link = "/contact"

[[params.social]]
icon = "fa-envelope"
# change the link after the public announcement
link = "mailto:contact@cloudnative.to"

[[params.social]]
icon = "fa-rss"
link = "https://cloudnative.to/blog/index.xml"

################################### English language #####################################
[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/en"
weight = 2
#home = "Home"
# footer content
footer_content = "Cloud Native Community is an neutral, cloud native end user community founded on May 12, 2020 by CNCF ambassadors and open source opinion leaders to promote cloud native technologies and build a developer ecosystem."
# copyright
copyright = "Copyright &copy; {year} Cloud Native Community"


################################### Chinese language #####################################
[Languages.zh]
languageName = "中文"
languageCode = "zh-cn"
contentDir = "content/zh"
weight = 1
#home = "主页"
# footer content
footer_content = "云原生社区是一个中立的云原生终端用户社区，由 CNCF 大使、开源意见领袖共同发起成立于 2020 年 5 月 12 日，旨在推广云原生技术，构建开发者生态。"
# copyright
copyright = "Copyright &copy; {year} 云原生社区"

########################### Chinese navigation ################################
# main menu
[[Languages.zh.menu.main]]
name = "社区"
weight = 2

[[Languages.zh.menu.main]]
parent = "社区"
name = "管理委员会"
URL = "/team"
weight = 1

[[Languages.zh.menu.main]]
parent = "社区"
name = "云原生学院"
URL = "https://i.cloudnative.to/academy/"
weight = 2

[[Languages.zh.menu.main]]
parent = "社区"
name = "城市站"
URL = "/city"
weight = 3

[[Languages.zh.menu.main]]
parent = "社区"
name = "社区资料"
URL = "https://i.cloudnative.to/community/"
weight = 4

[[Languages.zh.menu.main]]
name = "兴趣小组"
weight = 3

[[Languages.zh.menu.main]]
parent = "兴趣小组"
name = "Kubernetes SIG"
URL = "https://i.cloudnative.to/kubernetes/"
weight = 1

[[Languages.zh.menu.main]]
parent = "兴趣小组"
name = "Istio SIG"
URL = "https://i.cloudnative.to/istio/"
weight = 2

[[Languages.zh.menu.main]]
parent = "兴趣小组"
name = "Envoy SIG"
URL = "https://i.cloudnative.to/envoy/"
weight = 3

[[Languages.zh.menu.main]]
parent = "兴趣小组"
name = "Dapr SIG"
URL = "https://i.cloudnative.to/dapr/"
weight = 4

[[Languages.zh.menu.main]]
parent = "兴趣小组"
name = "OAM SIG"
URL = "https://i.cloudnative.to/oam/"
weight = 5

[[Languages.zh.menu.main]]
name = "博客"
weight = 4

[[Languages.zh.menu.main]]
parent = "博客"
name = "Kubernetes"
URL = "/categories/kubernetes"
weight = 1

[[Languages.zh.menu.main]]
parent = "博客"
name = "Service Mesh"
URL = "/categories/service-mesh"
weight = 2

[[Languages.zh.menu.main]]
parent = "博客"
name = "Envoy"
URL = "/categories/Envoy"
weight = 3

[[Languages.zh.menu.main]]
parent = "博客"
name = "OAM"
URL = "/categories/OAM"
weight = 4

[[Languages.zh.menu.main]]
parent = "博客"
name = "开源社区"
URL = "/categories/开源社区"
weight = 5

[[Languages.zh.menu.main]]
parent = "博客"
name = "所有"
URL = "/blog"
weight = 6

[[Languages.zh.menu.main]]
name = "资料"
weight = 5

[[Languages.zh.menu.main]]
parent = "资料"
name = "云原生生态图景"
URL = "http://landscape.opensourcecloud.cn/"
weight = 1

[[Languages.zh.menu.main]]
parent = "资料"
name = "云原生学院分享归档"
URL = "https://github.com/cloudnativeto/academy"
weight = 2

[[Languages.zh.menu.main]]
parent = "资料"
name = "Kubebuilder 中文文档"
URL = "/kubebuilder"
weight = 3

[[Languages.zh.menu.main]]
parent = "资料"
name = "Envoy 中文文档"
URL = "/envoy"
weight = 4

[[Languages.zh.menu.main]]
name = "关于"
weight = 6

[[Languages.zh.menu.main]]
parent = "关于"
name = "介绍"
URL = "about"
weight = 1

[[Languages.zh.menu.main]]
parent = "关于"
name = "联系"
URL = "contact"
weight = 2

[[Languages.zh.menu.main]]
name = "投稿"
URL = "contribute"
weight = 7

[[Languages.zh.menu.main]]
name = "招聘"
URL = "job"
weight = 8

# footer menu
[[Languages.zh.menu.footer]]
name = "声明与政策"
URL = "/code-of-conduct"
weight = 1

